### ISSUE TITLE
having trouble passing plugin lifecycle events.

### ISSUE THREAD

**Issue by nobotious** [djxy/SpongeJavaScript#1]
[new 1.txt](https://github.com/djxy/SpongeJavaScript/files/253051/new.1.txt)

just pasted the pre-init error, but it errors on all stages.

running forge-1.8.9-11.15.1.1855
running spongeforge-1.8.9-1855-4.1.0-BETA-1315
DjxyCore-1.0
SpongeJavaScript-2.0

**Comment by nobotious** [comment]
figured it out! nashorn isn't provided in the 2.0 download. i downloaded 1.0 and moved the nashorn jar into my mods directory.

**Comment by Cat121** [comment]
Great to know, I had no errors on loading but it might explains why I couldn't use the sample script.

Thanks for figuring out.

**Comment by djxy** [comment]
The release 2.0 now contain nashorn.jar
