### ISSUE TITLE
In docs page, link to JavaDocs links to API 3.0

### ISSUE THREAD

**Issue by pie-flavor** [djxy/SpongeJavaScript#3]
[here](https://github.com/djxy/SpongeJavaScript/wiki/How-to-use-SpongeJavaScript#how-to-use-java-objects) and [here](https://github.com/djxy/SpongeJavaScript/wiki/How-to-use-SpongeJavaScript#how-to-use-java-objects)

**Comment by djxy** [comment]
I will update it.
